export const TooltipText = {
  AddFile: '新建文件',
  RenameFile: '重命名',
  DeleteFile: '删除',
  isEntry: '入口文件',
  SetEntry: '设为入口文件',
  ToggleFiles: (show: boolean) => `${show ? '隐藏' : '显示'}文件栏`,
  ToggleCode: (show: boolean) => `${show ? '隐藏' : '显示'}代码编辑器`,
  Settings: '设置',
  ToggleWebPreview: (show: boolean) => `${show ? '隐藏' : '显示'}网页预览`,
  RefreshWebPreview: '刷新预览',
  AutoSave: '自动保存',
  SwapLayout: '切换代码编辑器和预览窗口的位置',
  CopyCode: '复制代码到剪贴板',
  Share: '分享页面',
  Docs: '查看 codeplayer 文档',
  Github: '在 github 上查看 codeplayer',
  LightDark: '切换主题色',
  Pane: '切换布局',
};
